default_platform(:ios)


if is_ci
  xcode_select("/Applications/Xcode_15.4.app")
end 

platform :ios do
  desc "Build and test app"
  lane :test do
    scan
  end

  desc "Deploy to App Store Connect"
  lane :deploy do |options|
    if ENV["BUILD_NUMBER"].nil? || ENV["BUILD_NUMBER"].empty?
      UI.important 'nothing to deploy'
      next
    end

    app_store_connect_api_key(
      key_id: ENV["KEY_ID"],
      issuer_id: ENV["ISSUER_ID"],
      key_content: ENV["KEY_VALUE"]
    )

    password = SecureRandom.hex
    keychain_name = "signing_temp"

    create_keychain(
      name: keychain_name,
      password: password,
      unlock: true
    )

    begin
      import_certificate(
        certificate_path: "distribution.p12",
        certificate_password: ENV["CERTIFICATE_PASSWORD"],
        keychain_password: password,
        keychain_name: keychain_name
      )

      increment_build_number(
        build_number: ENV["BUILD_NUMBER"]
      )

      get_provisioning_profile(
        readonly: true,
        app_identifier: "com.oliver-binns.General-Election-2017",
        provisioning_name: "General-Election-2017"
      )
      update_code_signing_settings(
        use_automatic_signing: false,
        code_sign_identity: "Apple Distribution",
        profile_name: "General-Election-2017",
        targets: "GeneralElection"
      )
      get_provisioning_profile(
        readonly: true,
        app_identifier: "com.oliver-binns.General-Election-2017.Stickers",
        provisioning_name: "General-Election-Stickers"
      )
      update_code_signing_settings(
        use_automatic_signing: false,
        code_sign_identity: "Apple Distribution",
        profile_name: "General-Election-Stickers",
        targets: "Stickers"
      )

      gym(
        export_method: "app-store",
        destination: "generic/platform=iOS",
        sdk: "iphoneos"
      )

      upload_to_testflight(
        skip_submission: true,
        app_platform: "ios"
      )
    ensure
      delete_keychain(name: keychain_name)
    end

  end
end
