default_platform(:ios)


if is_ci
  xcode_select("/Applications/Xcode_15.4.app")
end 

platform :ios do
  desc "Build and test app"
  lane :test do
    scan
  end

  desc "Deploy to App Store Connect"
  lane :deploy do |options|
    if ENV["BUILD_NUMBER"].nil? || ENV["BUILD_NUMBER"].empty?
      UI.important 'nothing to deploy'
      next
    end
  end
end
